tunnel: 7a32c54f-f326-40a5-8984-0ab49798562f
credentials-file: /root/.ivry/tunnel_credential.json

ingress:
  - hostname: model1.lormul.org
    service: http://localhost:3009
  - hostname: identifier-1.lormul.org
    service: http://localhost:3009    
  - service: http_status:404